weather/Models/DataModels/Weather.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weather.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weather
    {
        public int id { get; set; }
        public System.DateTime NextUpdate { get; set; }
        public System.DateTime DateEnd { get; set; }
        public System.DateTime DateFrom { get; set; }
        public string Temp { get; set; }
        public string Symbol { get; set; }
        public string Period { get; set; }
        public int GeoBaseId { get; set; }
        public int CityId { get; set; }
    
        public virtual City City { get; set; }
    }
}

weather/Models/Weather.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;

namespace weather.Models
{
    [MetadataType(typeof(Weather_Metadata))]
    public partial class Weather
    {

        public string cssSymbol { get { return GetSymbolCssText(Symbol); } }
        public string GetSymbolCssText(string symbolNumber)
        {
            string[] cssClas = { "null", "wi-day-sunny", "wi-day-cloudy", "wi-day-cloudy", "wi-cloudy",
                                   "wi-day-sprinkle", "wi-day-thunderstorm", "wi-day-rain-mix",
                                   "wi-day-snow", "wi-showers", "wi-rain", "wi-storm-showers",
                                   "wi-rain-mix", "wi-snow", "wi-snow", "wi-fog", "wi-day-sunny",
                                   "wi-day-cloudy", "wi-day-showers", "wi-day-snow", "wi-day-storm-showers",
                                   "wi-day-storm-showers", "wi-day-storm-showers", "wi-day-storm-showers"  };



            return cssClas[int.Parse(symbolNumber)];

        }
    }

    class Weather_Metadata
    {
        private string _symbol;
        

        public string GeoBaseId { get; set; }

        public DateTime NextUpdate { get; set; }
        public string Period { get; set; }
        
        public DateTime DateFrom { get; set; }

        public DateTime DateEnd { get; set; }

        public string Temp { get; set; }

        public string Symbol { get; set; }


       


    }
}

weather/ViewModels/WeatherViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using weather.Models;

namespace weather.ViewModels
{
    public class WeatherViewModel
    {


        public string State { get; set; }
        public int GeoNameId { get; set; }
        
        public City City { get; set; }
        public IEnumerable<City> Cities { get; set; }


        public bool HasCities { get { return Cities != null && Cities.Count() > 1; } }
        public bool HasWeather { get { return !HasCities; } }
        



        [Display(Name="Sök på ort")]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Sökordet måste var minst på 3 tecken!")]
        [Required(ErrorMessage="Du måste ange en ort")]
        public string SearchName { get; set; }

        public string Name { get; set; }
    }
}

weather/Controllers/WeatherController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using weather.Models;
using weather.Models.Repositories;
using weather.Models.WebServices;
using weather.Models.WebServices.Yr;
using weather.ViewModels;

namespace weather.Controllers
{
    public class WeatherController : Controller
    {
        //
        // GET: /
        private WeatherService _service = new WeatherService();


    
        public ActionResult Index()
        {
           
            return View("Index");
        }

        [HttpPost, ActionName("Index")]
        [ValidateAntiForgeryToken]
        public ActionResult search([Bind(Include="SearchName")] WeatherViewModel model)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    model.Cities = _service.SearchCities(model.SearchName);

                    if (model.Cities.Count() == 1)
                    {
                        return Redirect("/" + model.Cities.First().GeoNameId + "/" + model.Cities.First().State + "/" + model.Cities.First().Name);
                    }

                }
            }
            catch (Exception e)
            {
                
                ModelState.AddModelError(String.Empty, e.Message);
            }
            

            return View("Index", model);
        }




        public ActionResult weather([Bind(Include = "Geonameid, State, Name")] WeatherViewModel model)
        {
            ModelState.Remove("SearchName");
            try
            {

                if (ModelState.IsValid)
                {
                    model.City = _service.GetWeatherFromId(model.GeoNameId);
                }

                return View("Index", model);
            }
            catch (Exception e)
            {
                //throw e;
                ModelState.AddModelError(String.Empty, e.Message);
            }
            return View("Index", model);

        }


        
    }
}

weather/Views/Weather/CityList.cshtml
@model weather.ViewModels.WeatherViewModel



@if (Model != null)
{

       
    foreach (var city in Model.Cities)
    {
        
        <li>
            <a href="@city.GeoNameId/@city.State/@city.Name"> @city.State, @city.Name</a>
        </li>
  
    }
    
    
    
}

weather/Views/Weather/Index.cshtml
@model weather.ViewModels.WeatherViewModel

<h2>Vädersök</h2>

@using (@Html.BeginForm("Index", "Weather"))
{
    
        

        <div class="row">
            <div class="large-6 columns">
                <div class="row collapse">
                    <div class="small-9 columns">
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "Fel inträffade")
                        @Html.TextBoxFor(u => u.SearchName, new { placeholder = "Search eg. kalmar" } )
                        @Html.ValidationMessageFor(u => u.SearchName)
                    </div>
                    <div class="small-3 columns">
                        <input type="submit" value="Search" class="button postfix">
                    </div>
                </div>
            </div>
        </div>
    
}

@if (ViewData.ModelState.IsValid)
{
    

    if (Model != null  && Model.HasCities)
    {
        @Html.Partial("CityList", Model)  
      
    }
    if (Model != null && Model.HasWeather)
    {
        @Html.Partial("WeatherList", Model)
    }

    
}
@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

weather/Views/Weather/WeatherList.cshtml
@model weather.ViewModels.WeatherViewModel


@if (Model != null)
{
    
    <h2>Väder för @Model.City.State, @Model.City.Name</h2>
 
    <div class="row">
    
        @foreach (var weather in Model.City.Weathers)
        {
                        
                    <div class="large-2 columns weather-block">
                        

                        
                        <h3>@weather.DateFrom.ToString("dddd", new System.Globalization.CultureInfo("sv-SE"))</h3>
                        <p>@weather.DateFrom.ToString("HH:mm") - @weather.DateEnd.ToString("HH:mm")</p>
                        <div class="weather-symbol">
                            <i class="@weather.cssSymbol"></i>
                        </div>
    
                        <div class="large-12">
                            <div class="large-4 columns"><i class="wi-thermometer"></i> </div>
                            <div class="large-4 columns"><p class="temp">@weather.Temp</p></div>
                            <div class="large-4 columns"><i class="wi-celcius"></i></div>
                        </div>
                        
                    </div>

        }
        <div class="large-2 columns"></div>

    </div>
}
    